.TH "lo4-logger" "1" "July 2008"
.PP
.SH "NAME"
lo4-logger \- download LO4 files from a LX Navigation logger
.PP
.SH "SYNOPSIS"
.B lo4-logger
[\fIOPTION\fR]...
\fIFILE\fR
.SH DESCRIPTION
.PP
Download flights from an LX Navigation device (like LX4000) over the
serial port to the specified file.
.TP
\fB\-t\fR, \fB\-\-tty\fI=DEVICE\fR
Specify a device node different than /dev/ttyS0
.SH AUTHOR
Max Kellermann <max@duempel.org>
.SH COPYRIGHT
Copyright (C) 2004-2008 Max Kellermann
.br
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.  There is NO WARRANTY, to the
extent permitted by law.
.SH "SEE ALSO"
\fBlxn-logger\fR(1), \fBfilsertool\fR(1)
